name: Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
strategy:
  matrix:
    os: [ubuntu-latest]
    compiler: [gcc]

env:
  BUILD_TYPE: Release
  INSTALL_LOCATION: .local
  CONAN_SYSREQUIRES_MODE: enabled
  CXX: ${{ matrix.compiler }}
  

jobs:
  build:

    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup python
      uses: actions/setup-python@v2
    
    - name: Download Conan package manager.
      run: |
        python -m pip install --upgrade pip
        pip install conan
        pip install conan_package_tools
        export PATH=$PATH:/home/runner/.local/bin

    - name: configure
      run: cmake -B build -DCMAKE_INSTALL_PREFIX=./install -DCMAKE_BUILD_TYPE=Release
      
    - name: build
      run: cmake --build build --config Release -j4

    #- name: run tests
    #  run: |
    #    cd build
    #    ctest -C $BUILD_TYPE -VV
    # 
    #- name: install project
    #  run: cmake --build build --target install --config Release 
    #
    #- name: Code coverage using Codecov 
    #  run: bash <(curl -s https://codecov.io/bash) 
    
